on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: npm run build